### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by satyammpandeyy** [Yash094/Discord-audit-log-webhook#1]
CAN IT BE WITHOUT MONGO

**Comment by DarkGD123** [comment]
That would be impossible

**Comment by Yash094** [comment]
You can use [Tomato's bot](https://github.com/Tomato6966/discord-audit-log-webhook) it is without mongodb but it is made only for a single server.
Also Mongodb setup is very easy you can check my guide here - [Guide](https://github.com/shinchanOP/discord-audit-log-webhook/wiki/HOW-TO-USE-MONGODB)

**Comment by Yash094** [comment]
If you want it with some other database for multiple servers let me know, I can try.
also I don't think there will be  a way to use it without any database for multiple servers.

**Comment by satyammpandeyy** [comment]
Yes Dude I wana For Quick.DB

**Comment by Yash094** [comment]
Ok, I will create a new branch with quick.db soon

**Comment by satyammpandeyy** [comment]
Yea, Tysm Please Do it As Soon As Possible

**Comment by satyammpandeyy** [comment]
Did it's done?

**Comment by Yash094** [comment]
HERE IT IS - [LOGGER BOT QUICK.DB](https://github.com/shinchanOP/discord-audit-log-webhook/tree/Quick.db)
Please star the repo and follow me on github it helps a lot.

**Comment by satyammpandeyy** [comment]
Cool
