### ISSUE TITLE
(PrabhasDaily Check before you make any accusations )

### ISSUE THREAD

**Issue by oksouhhhhhhhhh** [Yash094/Discord-audit-log-webhook#4]

**Comment by Yash094** [comment]
For your kind information tomato made the bot with enmap database. I completely changed the DB to MongoDB and upload this Github. Check before you make any accusations & tomato is my good friend he also knows about this repo

**Comment by Yash094** [comment]
Tomato also added this repo in his GitHub here is the [link](https://github.com/Tomato6966/discord-audit-log-webhook-with-mongoose). ( check the description of the repo )
